name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "rekor-migration"
  workflow_dispatch:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Use Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Lint sources
        run: npm run lint
      - name: Check
        run: npm run format
