name: Multiple Architecture Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release/*"
    tags:
      - "v*"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ui-image-build:
    uses: ./.github/workflows/build-push-images.yaml
    with:
      registry: "ghcr.io"
      image_name: "${{ github.repository_owner }}/rhtas-console-ui"
      containerfile: "./Dockerfile"
      architectures: '[ "amd64", "arm64" ]'
      extra-args: "--ulimit nofile=4096:4096"
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}

  attestations:
    needs: ui-image-build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    steps:
      - name: Log in to registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 #v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/rhtas-console-ui
          subject-digest: ${{ needs.ui-image-build.outputs.digest }}
          push-to-registry: true
